{% set name = "opentelemetry-instrumentation-watsonx" %}
{% set version = "0.47.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: ff8bae433993fa1d85f55d4653ccc2bab722ee9976f69e489479a5de022dc967

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-semantic-conventions-ai >=0.4.13,<0.5
  run_constrained:
    - ibm-watson-machine-learning ==1.0.333

# Unable to run tests, ibm-watson-machine-learning is not in the main channel.
test:
  imports:
    - opentelemetry.instrumentation.watsonx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry IBM Watsonx Instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    This library allows tracing IBM Watsonx prompts and completions sent with
    the officialIBM Watson Machine Learning library and IBM watsonx.ai library.

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url
